### ISSUE TITLE
pieces dropped in Piece Tray not selected

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#54]
I expect pieces that are dropped into a Piece Tray to be selected, but that does not happen, both when the user is directly dropping pieces, and when playback shows pieces being dropped.

**Comment by DLLarson** [comment]
This doesn't happen in the official released version either so this will be a behavior change. However, it does select the pieces dragged onto the board.

I think this change makes sense though. 

I don't think anyone would be dependent on the non-selection of the pieces behavior and it's good to get feedback on what was actually dropped since a  piece stack obscures what's going to be dragged (although it's visible in the select list.)

-Dale

**Comment by wsu-cb** [comment]
> This doesn't happen in the official released version either so this will be a behavior change. However, it does select the pieces dragged onto the board.
> 
> I think this change makes sense though.
> 

I was aware that this was a change.  Should I have marked this as "enhancement" since it's different from CB 3.1, even though I personally think CB 3.1 behavior is "wrong"?

> I don't think anyone would be dependent on the non-selection of the pieces behavior and it's good to get feedback on what was actually dropped since a piece stack obscures what's going to be dragged (although it's visible in the select list.)
> 
> -Dale

**Comment by DLLarson** [comment]
>Should I have marked this as "enhancement" since it's different from CB 3.1

Nah... I think it qualifies as a bug even though it's a behavior change.

-Dale
