### ISSUE TITLE
Atom/AtomList/AtomID semantics

### ISSUE THREAD

**Issue by wsu-cb** [CyberBoardPBEM/cbwindows#66]
If I understand the Atom/AtomList/AtomID family correctly, it is C++98 code that can be handled in C++11 by std::forward_list<std::shared_ptr<T>>.  Is that correct?

If so, I will rewrite the Atom code that way.  Even if I'm not understanding it correctly, it still needs a rewrite to support 64bit because it has pointers being cast to 32bit values and back again.

**Comment by DLLarson** [comment]
The atom stuff attempts to mimic the atom facility buried deep within Win32. Atoms are used for a variety of things in windows where a string is registered with an OS table and returns a unique number. After which comparisons between any strings within the atom table can be compared by simply comparing a number. Here's more info on the facility:

https://docs.microsoft.com/en-us/windows/win32/dataxchg/about-atom-tables

For CB the concept is used to manage Fonts so that only a single "realization" of a font exists at a time. It was crucial for CB running under Win16 because of a severe lack of memory and CPU power. Each time a font is realized it must be rasterized to be used with a particular GDI instance. So if you're paint a board with a lot of different fonts it could increase rendering times. 

I don't see a problem with upscaling the numbers to 32bits.

I'm not so sure the semantics of a shared pointer alone totally covers what is described above.

I'm not against upgrading the implementation but still would like its goals to be achieved: avoiding redundant font realizations.

-Dale

**Comment by wsu-cb** [comment]
> For CB the concept is used to manage Fonts so that only a single "realization" of a font exists at a time. It was crucial for CB running under Win16 because of a severe lack of memory and CPU power. Each time a font is realized it must be rasterized to be used with a particular GDI instance. So if you're paint a board with a lot of different fonts it could increase rendering times.
> 
> I don't see a problem with upscaling the numbers to 32bits.
> 

The numbers are already 32bit, but for 64bit code to continue using the current design, they need to be increased to 64bits.



> I'm not so sure the semantics of a shared pointer alone totally covers what is described above.
> 

I proposed `std::forward_list<>` (a.k.a, singly-linked list) above to cover the parts of the semantics that shared pointers can't handle.  (That list use also implies needing to provide equality tests of the referenced objects as well, just as in the current design.)



> I'm not against upgrading the implementation but still would like its goals to be achieved: avoiding redundant font realizations.
> 

I think avoiding redundant fonts isn't a problem.  However, the replacement for `AtomID` in my proposed design is `std::shared_ptr<>`, and there is a slight penalty there.  `AtomID` in the current design can be implemented as a single `void*` (aka 64bit unsigned int, aka `uintptr_t`).  However, `std::shared_ptr<>` (or at least Microsoft's implementation) is actually a struct containing two pointers.  (Comparison of shared pointers still only requires a single pointer comparison.)  Is the extra storage for each `AtomID` a concern?

**Comment by DLLarson** [comment]
>The numbers are already 32bit, but for 64bit code to continue

I actually meant moving from 32 to 64 bits. When I said 16 bits I had just finished reviewing the MSoft docs for atoms and they used to use 16 bit numbers in Win16. I blame old person neural net leakage.

I'll note that the Atom stuff was the very first class I ever wrote as a young pup C++ coder way back when. It shouldn't be considered optimal.

> Is the extra storage for each AtomID a concern?

Nope. A single bitmap dwarfs most of this stuff. Storage in general isn't a concern for data other than bitmaps. In the early days CB used to only support 8 bit pixels via a fixed color palette just to be able to run on the Win16 systems. The atom stuff was also crucial.

-Dale
